---
- name: Setup Web and DB Server
  hosts: my_server
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Copy install.sh to remote server
      copy:
        src: ./install.sh
        dest: /install.sh
      become: true
    # - name: "Execute the script"
    #   command: sh /install.sh
