---
- name: Setup Web and DB Server
  hosts: my_server
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add ondrej/php repository for PHP 8.0
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        name: apache2
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP and Apache2
      apt:
        name: ["php7.4", "php8.2", "apache2", "libapache2-mod-php"]
        state: present

    # - name: Install MySQL Server
    #   apt:
    #     name: mysql-server

    # - name: Set MySQL root password
    #   command: sudo mysql -e " ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'ztech@448'";

    # - name: Install phpMyAdmin
    #   apt:
    #     name: phpmyadmin
    - name: Add Google Chrome repository key
      shell: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      ignore_errors: yes # Ignore errors temporarily
      register: chrome_key_result

    - name: Download Google Chrome repository key (if previous task failed)
      shell: |
        wget https://dl.google.com/linux/linux_signing_key.pub
      when: not ansible_check_mode and chrome_key_result|failed

    - name: Add Google Chrome repository
      lineinfile:
        path: /etc/apt/sources.list.d/google-chrome.list
        line: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      become: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present

    - name: Add AnyDesk repository key
      shell: |
        wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -

    - name: Add AnyDesk repository
      lineinfile:
        path: /etc/apt/sources.list.d/anydesk-stable.list
        line: "deb http://deb.anydesk.com/ all main"
      become: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install AnyDesk
      apt:
        name: anydesk
        state: present

    - name: Install snap package manager
      apt:
        name: snapd
        state: present

    - name: Install Skype via snap
      command: snap install skype

    - name: Install Visual Studio Code via snap
      command: snap install code --classic

    - name: Install PostgreSQL
      apt:
        name: postgresql

    - name: Set PostgreSQL password
      postgresql_user:
        db: postgres
        name: postgres
        password: ztech@44

    - name: Install phpPgAdmin
      apt:
        name: phppgadmin
